name: Python Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.5'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Add any other dependencies for testing, e.g., pytest or unittest
        pip install pytest  # Remove if using only unittest

    - name: Run tests
      run: |
        # Run tests with pytest or unittest
        pytest || python -m unittest discover

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ./test-reports/  
